name: Fencewatch
options:
  bundleIdPrefix: com.shimondeitel.fencewatch
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Fencewatch:
    type: application
    platform: iOS
    sources:
      - path: Fencewatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencewatch
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Fencewatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  FencewatchTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: FencewatchTests
      - path: Fencewatch.storekit
    dependencies:
      - target: Fencewatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencewatch.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  FencewatchUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: FencewatchUITests
    dependencies:
      - target: Fencewatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.fencewatch.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Fencewatch:
    build:
      targets:
        Fencewatch: all
        FencewatchTests: [test]
        FencewatchUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Fencewatch.storekit
    test:
      config: Debug
      storeKitConfiguration: Fencewatch.storekit
      targets:
        - FencewatchTests
        - FencewatchUITests
    archive:
      config: Release
